export const genres = [
  { id: 'action', name: 'Action' },
  { id: 'adventure', name: 'Adventure' },
  { id: 'anime', name: 'Anime' },
  { id: 'co-dai', name: 'Cổ Đại' },
  { id: 'comic', name: 'Comic' },
  { id: 'comedy', name: 'Comedy' },
  { id: 'cooking', name: 'Cooking' },
  { id: 'chuyen-sinh', name: 'Chuyển Sinh' },
  { id: 'dam-my', name: 'Đam Mỹ' },
  { id: 'doujinshi', name: 'Doujinshi' },
  { id: 'drama', name: 'Drama' },
  { id: 'fantasy', name: 'Fantasy' },
  { id: 'gender-bender', name: 'Gender Bender' },
  { id: 'he-thong', name: 'Hệ Thống' },
  { id: 'historical', name: 'Historical' },
  { id: 'horror', name: 'Horror' },
  { id: 'live-action', name: 'Live action' },
  { id: 'manga', name: 'Manga' },
  { id: 'manhwa', name: 'Manhwa' },
  { id: 'manhua', name: 'Manhua' },
  { id: 'martial-arts', name: 'Martial Arts' },
  { id: 'mecha', name: 'Mecha' },
  { id: 'mystery', name: 'Mystery' },
  { id: 'ngon-tinh', name: 'Ngôn Tình' },
  { id: 'psychological', name: 'Psychological' },
  { id: 'romance', name: 'Romance' },
  { id: 'school-life', name: 'School Life' },
  { id: 'sci-fi', name: 'Sci-fi' },
  { id: 'shoujo', name: 'Shoujo' },
  { id: 'shoujo-ai', name: 'Shoujo Ai' },
  { id: 'shounen', name: 'Shounen' },
  { id: 'shounen-ai', name: 'Shounen Ai' },
  { id: 'slice-of-life', name: 'Slice of Life' },
  { id: 'sports', name: 'Sports' },
  { id: 'supernatural', name: 'Supernatural' },
  { id: 'thieu-nhi', name: 'Thiếu Nhi' },
  { id: 'tragedy', name: 'Tragedy' },
  { id: 'trinh-tham', name: 'Trinh Thám' },
  { id: 'truyen-mau', name: 'Truyện Màu' },
  { id: 'truyen-scan', name: 'Truyện scan' },
  { id: 'webtoon', name: 'Webtoon' },
  { id: 'xuyen-khong', name: 'Xuyên Không' }
] as const

export type GenreType = (typeof genres)[number]['id']
