export const PATH_MAPPING_API = {
  home: '/',
  genres: '/genres',
  comics: '/info',
  new: '/new-comics',
  top: '/top',
  type: ':type',
  name: ':id',
  idChapter: ':idChapter',
  daily: '/daily',
  weekly: '/weekly',
  monthly: '/monthly',
  chapter: '/chapter',
  follow: '/follow',
  comment: '/comment',
  comments: '/comments',
  recent: '/recent-update-comics',
  recommend: '/recommend-comics',
  popular: '/trending-comics',
  completed: '/completed-comics',
  boy: '/boy-comics',
  girl: '/girl-comics',
  chapters: '/chapters',
  search: '/search',
  download: '/download',
  history: '/history',
  searchSuggest: '/suggest',
  banner: '/get-all-banner'
} as const

export const PATH = {
  home: '/',
  genres: '/the-loai',
  comics: '/truyen-tranh',
  new: '/truyen-moi',
  top: '/bang-xep-hang',
  type: ':type',
  name: ':comicIndentify',
  idChapter: ':idChapter',
  daily: '/ngay',
  weekly: '/tuan',
  monthly: '/thang',
  chapter: '/chuong',
  follow: '/theo-doi',
  comment: '/binh-luan',
  comments: '/danh-sach-binh-luan',
  recent: '/truyen-moi-cap-nhat',
  recommend: '/truyen-nhanh',
  popular: '/truyen-noi-bat',
  completed: '/truyen-hoan-thanh',
  boy: '/truyen-con-trai',
  girl: '/truyen-con-gai',
  chapters: '/danh-sach-chuong',
  search: '/tim-kiem',
  download: '/tai-truyen',
  history: '/lich-su-doc-truyen',
  searchSuggest: '/goi-y-tim-kiem',
  slugChapter: ':slugChapter',
  slugComic: ':slugComic',
  privatePolicy: '/chinh-sach-bao-mat',
  app: '/gioi-thieu-ung-dung',
  login: '/dang-nhap',
  signup: '/dang-ky',
  customerInfo: '/thong-tin-ca-nhan',
  forgotPassword: '/quen-mat-khau',
  googleCallback: '/google-callback',
  mobileLogin: '/mobile-login',
  sitemap: '/so-do-trang-web'
} as const

export const API_MAPPING_PATH = {
  [PATH.home]: PATH_MAPPING_API.home,
  [PATH.genres]: PATH_MAPPING_API.genres,
  [PATH.comics]: PATH_MAPPING_API.comics,
  [PATH.new]: PATH_MAPPING_API.new,
  [PATH.top]: PATH_MAPPING_API.top,
  [PATH.type]: PATH_MAPPING_API.type,
  [PATH.name]: PATH_MAPPING_API.name,
  [PATH.idChapter]: PATH_MAPPING_API.idChapter,
  [PATH.daily]: PATH_MAPPING_API.daily,
  [PATH.weekly]: PATH_MAPPING_API.weekly,
  [PATH.monthly]: PATH_MAPPING_API.monthly,
  [PATH.chapter]: PATH_MAPPING_API.chapter,
  [PATH.follow]: PATH_MAPPING_API.follow,
  [PATH.comment]: PATH_MAPPING_API.comment,
  [PATH.comments]: PATH_MAPPING_API.comments,
  [PATH.recent]: PATH_MAPPING_API.recent,
  [PATH.recommend]: PATH_MAPPING_API.recommend,
  [PATH.popular]: PATH_MAPPING_API.popular,
  [PATH.completed]: PATH_MAPPING_API.completed,
  [PATH.boy]: PATH_MAPPING_API.boy,
  [PATH.girl]: PATH_MAPPING_API.girl,
  [PATH.chapters]: PATH_MAPPING_API.chapters,
  [PATH.search]: PATH_MAPPING_API.search,
  [PATH.download]: PATH_MAPPING_API.download,
  [PATH.history]: PATH_MAPPING_API.history,
  [PATH.searchSuggest]: PATH_MAPPING_API.searchSuggest
}

export default PATH
